---
layout: post
title:  _A Warning About Money_
book_author: Agustina Bazterrica
date:   2026-07-29 10:00:00 +0700
categories: 18+
image: tenderistheflesh.jpg
published: true
---
#A Warning About Money

Agustina Bazterrica’s novel, *Tender is the Flesh* (2017), highlights how the prioritization of money can drive people to the lowest depths of depravity. In the story, a virus makes all animals both inedible and dangerous to humans. People can, for example, no longer eat beef or keep dogs as pets. People try to completely rid the world of animals, and begin to breed other humans for consumption. These bred humans, which society euphemistically refers to as “head,” instead of humans, move from breeding centers to processing plants to butcher shops, game reserves, or laboratories. One man, Marcos Tejo, witnesses the brutal killing of humans and animals, and hates what he sees. Like many others, however, Marcos does not speak out against the injustices in his society. Marcos and other people he knows, the businesses in his country, and his country’s government continue to act violently and immorally in order to benefit financially.

##Individual

In *Tender is the Flesh*, individuals insist that their families need money, and thus try to justify the harm they cause to other people. While at work at the human processing plant, Marcos Tejo “...questions, yet again, why he exposes himself to this. The answer is always the same. He knows why he does this work. Because he’s the best and they pay him accordingly, because he doesn’t know how to do anything else, and because his father’s health depends on it” (p. 14). Marcos often wonders why he works at the human processing plant. Just as often, however, he reminds himself that he can and must endure his aversion to the work because of the financial reward. Marcos knows that his experience and expertise in the industry make his skills valuable, and he appreciates that his employer compensates him handsomely. He reasons that he does not have the same high value in any other field, and clearly does not want to begin a different line of work with an inevitable pay cut. Marcos tells himself that he must continue to work at the processing plant in order to afford the best care facility for his father. Marcos feels more comfortable with the violence he commits against others when he assures himself that he needs the money for his father. An esteemed colleague of Marcos’s at the plant, Sergio, feels and acts similarly. Marcos asks Sergio why Sergio does the especially gruesome work of a stunner (the person who knocks humans unconscious before their slaughter). Sergio answers, “...it was either the head or his family. It was the only thing he knew how to do and it paid well. Whenever he felt remorse he thought of his children and how the work enabled him to give them a better life” (p. 61). Like Marcos, Sergio behaves as if he has only two choices: work at the plant or fail his family. Sergio claims to know only one job well, and appreciates the good salary he is able to earn. When Sergio feels guilty about the violence he enacts on a daily basis, he quickly dispels any feelings of regret. He convinces himself that he bludgeons people so he can make money to provide for his children. To Sergio, the violence he enacts is for a good cause, and therefore becomes logical. One butcher shop employee explains to Marcos that “He just wanted to do honest work so he could support his family…he’d never felt so sick and miserable. And he couldn’t look the customers in the eye…he had to sell them rotten meat, and afterward he couldn’t sleep because of the guilt” (p. 32). The employee explains that his goal is to support his family. He feels terrible because he sells bad meat to customers, and he knows his deceit is shameful. The man says he knows that he fools and defiles other families, and continues to do this anyway, in order to make money for his own family. Throughout the novel, individuals forsake others and make the excuse that they have a family for which they need to provide.

##Business

In Marcos’s world, businesses solely consider the financial costs and benefits when they make decisions. They leave morality out of the equation. Marcos explains to one employee about a practice at the processing plant: “If [sick head] get better, they return to slaughter cycle, and if they don’t, they’re discarded…becuase transport is expensive. The breeding center is notified of the head that had to be thrown out and later they’re discounted” Efforts are made to preserve the humans that arrive at the plant from the breeding center because they are expensive. However, the plant allows the humans to live only as long as their survival makes financial sense. The plant does not provide long-term care to any sick humans from the breeding center because the plant deems that care too costly. The plant does not return the humans to the breeding center, or move them anywhere else, because the plant does not want to pay for their transportation. The plant does communicate with the breeding center when it exterminates humans that arrive sick because the plant wants the reimbursements. Expenditures regarding the sick humans’ extended time at the plant, transportation, and death are the sole considerations of the plant. Marcos thinks about “...an old show where the participants have to kill cats with a stick…to win a car. The audience applauds” (p. 47). In this case, the entertainment industry recognizes that there are people who are willing to terrorize and brutally kill small, defenseless animals, and other people who want to watch those actions. The producers decide to capitalize on that reality. The cat hunters put aside any moral problems they may have, and agree to personally abuse and kill cats so they can win a car. Other people encourage and reward the behavior. The creator of another violent business venture tells Marcos, “...fate has smiled down upon me. Some time ago, I implemented a program that allows celebrities who have fallen from grace by amassing large debts to settle their accounts here…if the hunters aren’t able to get them and they survive the adventure, I guarantee the cancellation of all their debt” (p. 141). The entrepreneur Urlet, who runs the game reserve, avoids personal responsibility for his actions when he credits fate for his business. Urlet claims that this financial success reflects a divine intervention and good luck. Like the creators of the cat show, Urlet decides to capitalize on violence. Some celebrities are so desperate for money that they risk their own lives and take on the roles of prey in exchange for financial reward. Other people pay money to hunt the celebrities. Large meat processing companies, media entertainment companies, and game reserves like Urlet’s do not worry about the degradation of humans and animals as long as they make money.

##Government

Just as individuals and businesses succumb to the promise of money, so too does the government. The consumption of human meat becomes acceptable in the first place because “Legalization occurred when the governments gave in to pressure from a big-money industry that had come to a halt. They adapted the processing plants and regulations. Not long after, they began to breed people as animals to supply the massive demand for meat” (p. 6). With the loss of animals, the lucrative meat industry faces collapse. The meat industry pivots quickly, and has the money and power to convince the government to agree with its solution. The meat industry knows that people want meat, and that the industry can continue to make money. Thus, the meat industry uses its monetary power to make the consumption of humans legal. Another organization that uses its financial power to get what it wants from the government is the Church of the Immolation: “The church fought for years until the government gave in and the two sides signed an agreement. Their success occurred only after the addition of a member who had high-ranking contacts and a lot of means” (p. 130). The Church of the Immolation sacrifices willing church members for consumption. The church’s practices make the government uncomfortable because of the social taboo against the consumption of a person with a name, not bred to be meat. The government finally capitulates to the church, however, because someone joins the church who “who had high ranking contacts and a lot of means,” someone who is able to offer enough money to a decision maker. The church gets its way because it is finally able to pay for the government’s submission. Guerrero Iraola, a man who works with one of the largest breeding centers that Marcos knows, explains how anything can become available for the right price: “It’s extremely pricey but the option exists, even if it’s illegal. Everyone is involved: politicians, the police, judges. Each takes their cut…” (p. 146). Guerrero reveals how the government is made up of individuals who are susceptible to bribery like everyone else. People in positions of power in the government, “Politicians, police officers, and judges,” quietly condone illegal activity that victimizes other people in exchange for money. Various examples throughout the story illustrate how promises of money can influence the government to change or ignore the law. 

*Tender is the Flesh* serves as a warning. When people simply want to make as much money as they possibly can, all other considerations such as morality can disappear, and people learn to justify anything for the accumulation of capital. On the individual level, people in the story accept and continue work that troubles them in exchange for a satisfactory pay check which they argue they need for their families. Marcos says his aging father depends on him, Sergio explains that his work provides for his children, and the butcher shop employee wants to support his family. All three men accept salaries in exchange for work that sacrifices the well-being of others. The men use their families as excuses for their behavior. In the business world, the singular consideration is revenue. Marcos looks at specific endeavors in meat processing, television, and hunting industries, and sees that decisions reflect the desire to profit, regardless of harm. Businesses act unbridled by any moral considerations such as the safety or dignity of humans and animals. The government also abandons its duty to justice in favor of money. People in government accept financial offerings to change laws or to make exceptions when some break the law. *Tender is the Flesh* warns that when money drives individuals and systems above all else, society fails.

References

Bazterrica, A. (2017). *Tender is the flesh*. (S. Moses, Trans.). Scribner
